name: Context Examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
       
      - name: "My step"
        run: echo "hello $MY_ACTION"
        env:
           MY_ACTION: ${{github.action_path}}
