name: Context Examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
       
      - name: "My step"
        run: |
         echo "hello $MY_ACTION"
         echo "hello $MY_ACTION_REF"
     
        env:
           MY_ACTION: ${{github.action_path}}
           MY_ACTION_REF: ${{github.action_ref}}
