name: "Workflow Commands"
on: ["push"]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo ":: group::my mesasge "
          echo "msg1"
          echo "msg2"
          echo "::enf=dgroup::"


